"""Transport-neutral server contracts for future HTTP/MCP integrations."""

from aegis_code.server.contracts import (
    API_VERSION,
    ApplyCheckRequest,
    ApplyConfirmRequest,
    ApplyResponse,
    PatchRequest,
    PatchResponse,
    ReportRequest,
    ReportResponse,
    SetupCheckRequest,
    SetupCheckResponse,
    StatusRequest,
    StatusResponse,
    apply_result_to_dict,
    patch_proposal_to_dict,
    run_report_to_dict,
    run_status_to_dict,
    setup_status_to_dict,
    to_error,
    to_response,
)
from aegis_code.server.handlers import (
    apply_check_handler,
    apply_confirm_handler,
    health_handler,
    latest_diff_handler,
    patch_handler,
    report_handler,
    setup_check_handler,
    status_handler,
)
from aegis_code.server.mcp import ToolDefinition, get_tool, invoke_tool, list_tools
from aegis_code.server.mcp_runtime import call_tool, list_tools as runtime_list_tools

__all__ = [
    "API_VERSION",
    "SetupCheckRequest",
    "PatchRequest",
    "ApplyCheckRequest",
    "ApplyConfirmRequest",
    "StatusRequest",
    "ReportRequest",
    "SetupCheckResponse",
    "PatchResponse",
    "ApplyResponse",
    "StatusResponse",
    "ReportResponse",
    "setup_status_to_dict",
    "patch_proposal_to_dict",
    "apply_result_to_dict",
    "run_status_to_dict",
    "run_report_to_dict",
    "to_response",
    "to_error",
    "health_handler",
    "setup_check_handler",
    "status_handler",
    "report_handler",
    "latest_diff_handler",
    "patch_handler",
    "apply_check_handler",
    "apply_confirm_handler",
    "ToolDefinition",
    "list_tools",
    "get_tool",
    "invoke_tool",
    "runtime_list_tools",
    "call_tool",
]
