from __future__ import annotations

from aegis_code.operations.contract import OperationContract, normalize_operation_contract
from aegis_code.operations.runner import (
    OperationDependencies,
    OperationRequest,
    OperationResult,
    run_operation,
)
from aegis_code.operations.append import run_append_operation
from aegis_code.operations.create_file import (
    _build_create_file_diff,
    _parse_create_file_provider_response,
    _target_exists,
    _validate_create_file_diff,
    run_create_file_operation,
)
from aegis_code.operations.insert import (
    _build_insert_after_diff,
    _insert_after_anchor,
    insert_before_index,
    insert_after_index,
    _parse_insert_provider_response,
    resolve_insert_after_index,
    run_insert_before_operation,
    run_insert_after_operation,
    _validate_insert_diff,
)
from aegis_code.operations.replace_block import (
    _build_replace_block_diff,
    _parse_replace_block_provider_response,
    _validate_replace_block_diff,
    replace_block_span,
    resolve_replace_block_span,
    run_replace_block_operation,
)
from aegis_code.operations.delete_block import run_delete_block_operation
from aegis_code.operations.delete_file import (
    _build_delete_file_diff,
    _validate_delete_file_diff,
    run_delete_file_operation,
)
from aegis_code.operations.rename_file import (
    _build_rename_file_diff,
    _validate_rename_file_diff,
    run_rename_file_operation,
)
from aegis_code.operations.move_file import run_move_file_operation
from aegis_code.operations.registry import (
    OperationDefinition,
    OPERATIONS,
    get_operation,
    is_supported_operation,
    list_operation_names,
    list_provider_free_operations,
    list_provider_required_operations,
)
from aegis_code.operations.delete_symbol import (
    _build_delete_symbol_diff,
    _validate_delete_symbol_diff,
    delete_symbol_span,
    run_delete_symbol_operation,
)
from aegis_code.operations.replace_file import (
    _build_replace_file_diff,
    _parse_replace_file_provider_response,
    _validate_replace_file_diff,
    run_replace_file_operation,
)
from aegis_code.operations.replace_symbol import (
    _build_replace_symbol_diff,
    _parse_replace_symbol_provider_response,
    _validate_replace_symbol_diff,
    replace_symbol_span,
    resolve_symbol_span,
    run_replace_symbol_operation,
)
from aegis_code.operations.errors import (
    APPEND_OUTPUT_INVALID,
    APPEND_SEMANTIC_SUSPICIOUS,
    APPEND_SOURCE_CONFLICT,
    APPEND_SYNTAX_INVALID,
    INVALID_APPEND_OPERATION,
    NO_APPEND_NEEDED,
    INSERT_OUTPUT_INVALID,
    OPERATION_ANCHOR_AMBIGUOUS,
    OPERATION_ANCHOR_NOT_FOUND,
    OPERATION_BUDGET_EXCEEDED,
    OPERATION_CONTRACT_INVALID,
    OPERATION_POLICY_BLOCKED,
    OPERATION_SYMBOL_AMBIGUOUS,
    OPERATION_SYMBOL_NOT_FOUND,
    OPERATION_TARGET_EXISTS,
    OPERATION_TARGET_MISSING,
    OPERATION_VALIDATION_FAILED,
    REPLACE_BLOCK_OUTPUT_INVALID,
    REPLACE_FILE_OUTPUT_INVALID,
    REPLACE_SYMBOL_OUTPUT_INVALID,
    CREATE_FILE_OUTPUT_INVALID,
)

__all__ = [
    "OperationContract",
    "OperationDependencies",
    "OperationRequest",
    "OperationResult",
    "normalize_operation_contract",
    "run_operation",
    "run_append_operation",
    "run_create_file_operation",
    "run_insert_after_operation",
    "run_insert_before_operation",
    "run_replace_block_operation",
    "run_delete_block_operation",
    "run_delete_file_operation",
    "run_rename_file_operation",
    "run_move_file_operation",
    "OperationDefinition",
    "OPERATIONS",
    "get_operation",
    "is_supported_operation",
    "list_operation_names",
    "list_provider_required_operations",
    "list_provider_free_operations",
    "run_replace_file_operation",
    "run_replace_symbol_operation",
    "run_delete_symbol_operation",
    "OPERATION_CONTRACT_INVALID",
    "OPERATION_TARGET_MISSING",
    "OPERATION_ANCHOR_NOT_FOUND",
    "OPERATION_ANCHOR_AMBIGUOUS",
    "OPERATION_SYMBOL_NOT_FOUND",
    "OPERATION_SYMBOL_AMBIGUOUS",
    "OPERATION_BUDGET_EXCEEDED",
    "OPERATION_VALIDATION_FAILED",
    "OPERATION_POLICY_BLOCKED",
    "OPERATION_TARGET_EXISTS",
    "CREATE_FILE_OUTPUT_INVALID",
    "INSERT_OUTPUT_INVALID",
    "REPLACE_BLOCK_OUTPUT_INVALID",
    "REPLACE_FILE_OUTPUT_INVALID",
    "REPLACE_SYMBOL_OUTPUT_INVALID",
    "APPEND_OUTPUT_INVALID",
    "APPEND_SYNTAX_INVALID",
    "APPEND_SEMANTIC_SUSPICIOUS",
    "INVALID_APPEND_OPERATION",
    "APPEND_SOURCE_CONFLICT",
    "NO_APPEND_NEEDED",
    "_parse_create_file_provider_response",
    "_build_create_file_diff",
    "_target_exists",
    "_validate_create_file_diff",
    "_parse_insert_provider_response",
    "_insert_after_anchor",
    "insert_before_index",
    "resolve_insert_after_index",
    "insert_after_index",
    "_build_insert_after_diff",
    "_validate_insert_diff",
    "_parse_replace_block_provider_response",
    "_build_replace_block_diff",
    "_validate_replace_block_diff",
    "_build_delete_file_diff",
    "_validate_delete_file_diff",
    "_build_rename_file_diff",
    "_validate_rename_file_diff",
    "_build_delete_symbol_diff",
    "_validate_delete_symbol_diff",
    "_parse_replace_file_provider_response",
    "_build_replace_file_diff",
    "_validate_replace_file_diff",
    "_parse_replace_symbol_provider_response",
    "_build_replace_symbol_diff",
    "_validate_replace_symbol_diff",
    "resolve_replace_block_span",
    "replace_block_span",
    "resolve_symbol_span",
    "replace_symbol_span",
    "delete_symbol_span",
]
