from __future__ import annotations

from pathlib import Path
from typing import Any


def _scaffold_files(stack_name: str, idea: str, test_command: str) -> dict[str, str]:
    project_model = (
        "# Project Model\n\n"
        f"Idea: {idea}\n\n"
        "## Scope\n"
        "- Initial scaffold created by aegis-code create.\n"
        "- Keep this file updated as architecture evolves.\n"
    )
    config_yaml = (
        "mode: balanced\n"
        "budget_per_task: 1.0\n"
        "models:\n"
        "  cheap: openai:gpt-4.1-nano\n"
        "  mid: openai:gpt-4.1-mini\n"
        "  premium: openai:gpt-4.1\n"
        "commands:\n"
        f"  test: \"{test_command}\"\n"
        "  lint: \"\"\n"
        "aegis:\n"
        "  base_url: \"https://aegis-backend-production-4b47.up.railway.app\"\n"
        "providers:\n"
        "  enabled: false\n"
        "  provider: \"openai\"\n"
        "  api_key_env: \"OPENAI_API_KEY\"\n"
        "patches:\n"
        "  generate_diff: false\n"
        "  max_context_chars: 12000\n"
        "  output_file: \".aegis/runs/latest.diff\"\n"
    )
    common = {
        ".aegis/aegis-code.yml": config_yaml,
        ".aegis/project_model.md": project_model,
    }
    if stack_name == "python-fastapi":
        return {
            **common,
            "app/main.py": "from fastapi import FastAPI\n\napp = FastAPI()\n\n\n@app.get('/')\ndef read_root() -> dict[str, str]:\n    return {'status': 'ok'}\n",
            "app/routes.py": "from fastapi import APIRouter\n\nrouter = APIRouter()\n",
            "app/models.py": "from pydantic import BaseModel\n\n\nclass Health(BaseModel):\n    status: str\n",
            "tests/test_app.py": "from app.main import app\n\n\ndef test_app_object_exists() -> None:\n    assert app is not None\n",
        }
    if stack_name == "python-cli":
        return {
            **common,
            "src/main.py": "def main() -> None:\n    print('hello from cli')\n\n\nif __name__ == '__main__':\n    main()\n",
            "tests/test_cli.py": "def test_cli_placeholder() -> None:\n    assert True\n",
            "README.md": "# Project\n\nGenerated by aegis-code create.\n",
        }
    if stack_name == "node-react":
        return {
            **common,
            "src/App.jsx": "export default function App() {\n  return <h1>Hello from React</h1>;\n}\n",
            "src/main.jsx": "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App';\n\ncreateRoot(document.getElementById('root')).render(<App />);\n",
            "tests/App.test.jsx": "import { describe, it, expect } from 'vitest';\n\ndescribe('app', () => {\n  it('placeholder', () => {\n    expect(true).toBe(true);\n  });\n});\n",
            "package.json": "{\n  \"name\": \"aegis-project\",\n  \"version\": \"0.1.0\",\n  \"private\": true,\n  \"scripts\": {\n    \"test\": \"vitest run\"\n  }\n}\n",
        }
    return {
        **common,
        "src/main.py": "def main() -> str:\n    return 'hello world'\n\n\nif __name__ == '__main__':\n    print(main())\n",
        "tests/test_main.py": "from src.main import main\n\n\ndef test_main() -> None:\n    assert main() == 'hello world'\n",
        "README.md": "# Project\n\nGenerated by aegis-code create.\n",
    }


def create_scaffold(
    *,
    target: Path,
    cwd: Path,
    stack_name: str,
    idea: str,
    test_command: str,
    confirm: bool,
) -> dict[str, Any]:
    resolved_cwd = cwd.resolve()
    resolved_target = target.resolve()
    if resolved_target == resolved_cwd:
        return {"ok": False, "code": 2, "message": "Refusing scaffold: target must not be the current repository root."}

    if target.exists() and any(target.iterdir()):
        return {"ok": False, "code": 2, "message": "Refusing scaffold: target exists and is not empty."}

    files = _scaffold_files(stack_name=stack_name, idea=idea, test_command=test_command)
    if not confirm:
        return {
            "ok": False,
            "code": 1,
            "message": "Scaffold preview only. Re-run with --confirm to write files.",
            "files": sorted(files.keys()),
            "target": str(target),
        }

    target.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    for rel_path, content in files.items():
        path = target / rel_path
        if path.exists():
            return {"ok": False, "code": 2, "message": f"Refusing scaffold: file already exists: {rel_path}"}
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(rel_path)
    return {"ok": True, "code": 0, "message": "Scaffold created.", "written": sorted(written), "target": str(target)}
